### ISSUE TITLE
Issue With Dell H310 

### ISSUE THREAD

**Issue by aki263** [Confusingboat/flash-it#15]
Server: Dell R720XD 
Card: Dell H310(Full Size PCI Card, this is not mini monolithic card)

Issue:
Every time I run script, it says 

> Could not retrieve PCI address from lspci, attempting to load from existing backup file.

I tried manually as well https://i.imgur.com/dT5l1tV.png

Ubuntu 18.04(installed on USB) booted in BIOS mode, tried with UEFI, same issue. I tried running live Ubuntu as well.

**Comment by Confusingboat** [comment]
From the screenshot it looks like that card is already flashed. In its base form `flash-it` is only compatible with cards that have the stock Dell firmware.

Similar to #9

**Comment by aki263** [comment]
Can I restore it back to Dell Stock firmware? During boot it shows H310 https://i.imgur.com/DkK4DKp.png

**Comment by aki263** [comment]
Ignore the last comment, looks like it worked. I changed the 

> ADAPTER_PATTERN="H310" to ADAPTER_PATTERN="LSI"

The process went ahead and completed successfully. https://i.imgur.com/t4p5TTy.png https://i.imgur.com/qCnAQ9u.png

@Confusingboat Thanks for help.

**Comment by Confusingboat** [comment]
Excellent! I'm glad it worked with just changing that, and that's actually very valuable input for a future change that will allow this to work out of the box with already-flashed devices.

Thanks for the testing and followup @aki263

**Comment by aki263** [comment]
For anyone looking for logs

> aki@aki-PowerEdge-R720xd:~$ nano  flash-it.sh
> aki@aki-PowerEdge-R720xd:~$ ./flash-it.sh
> Error: must run as root/su
> aki@aki-PowerEdge-R720xd:~$ sudo ./flash-it.sh
> [sudo] password for aki:
> find: ‘/tmp/lsi_firmware’: No such file or directory
> find: ‘/tmp/lsi_firmware’: No such file or directory
> find: ‘/tmp/lsi_uefi’: No such file or directory
> Hit:1 http://in.archive.ubuntu.com/ubuntu bionic InRelease
> Hit:2 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease
> Hit:3 http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease
> Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
> Get:5 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11 Metadata [46.0 kB]
> Get:6 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 DEP-11 Metadata [49.2 kB]
> Get:7 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 DEP-11 Metadata [2,464 B]
> Fetched 186 kB in 1s (134 kB/s)
> 
> 
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> 22 packages can be upgraded. Run 'apt list --upgradable' to see them.
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Note, selecting 'git' instead of 'git-core'
> build-essential is already the newest version (12.4ubuntu1).
> unzip is already the newest version (6.0-21ubuntu1).
> p7zip-full is already the newest version (16.02+dfsg-6).
> sysfsutils is already the newest version (2.1.0+repack-4build1).
> git is already the newest version (1:2.17.1-1ubuntu0.7).
> pciutils is already the newest version (1:3.5.2-1ubuntu1.1).
> python3 is already the newest version (3.6.7-1~18.04).
> 0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
> Archive:  firmware.zip
>    creating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/Firmware/
>    creating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/Firmware/HBA_9211_8i_IR/
>   inflating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/Firmware/HBA_9211_8i_IR/2118ir.bin
>    creating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/Firmware/HBA_9211_8i_IT/
>   inflating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/Firmware/HBA_9211_8i_IT/2118it.bin
>   inflating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/README_9211_8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows.txt
>   inflating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/SAS2BIOS_Phase20.0-7.39.02.00.pdf
>    creating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/sas2flash_dos_rel/
>   inflating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/sas2flash_dos_rel/sas2flsh.exe
>   inflating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/SAS2FLASH_Phase20.0-20.00.00.00.pdf
>   inflating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/SAS2Flash_ReferenceGuide.pdf
>    creating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/sas2flash_win_x64_rel/
>   inflating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/sas2flash_win_x64_rel/sas2flash.exe
>    creating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/sas2flash_win_x86_rel/
>   inflating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/sas2flash_win_x86_rel/sas2flash.exe
>   inflating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/SAS2FW_Phase20-20.00.07.00 Release Notes.pdf
>    creating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/sasbios_rel/
>   inflating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/sasbios_rel/mptbios.txt
>   inflating: /tmp/lsi_firmware/9211-8i_Package_P20_IR_IT_FW_BIOS_for_MSDOS_Windows/sasbios_rel/mptsas2.rom
> Archive:  uefi.zip
>   inflating: /tmp/lsi_uefi/UEFI_BSD_P20/UEFI_BSD_HII_SAS2_Phase20.0-7.27.01.01.pdf
>    creating: /tmp/lsi_uefi/UEFI_BSD_P20/uefi_bsd_rel/
>   inflating: /tmp/lsi_uefi/UEFI_BSD_P20/uefi_bsd_rel/DriverSignInfo.txt
>   inflating: /tmp/lsi_uefi/UEFI_BSD_P20/uefi_bsd_rel/ebcsas2.efi
>   inflating: /tmp/lsi_uefi/UEFI_BSD_P20/uefi_bsd_rel/ebcsas2.rom
>   inflating: /tmp/lsi_uefi/UEFI_BSD_P20/uefi_bsd_rel/readme_SAS2_UEFI_BSD_HII.txt
>    creating: /tmp/lsi_uefi/UEFI_BSD_P20/uefi_bsd_rel/Signed/
>   inflating: /tmp/lsi_uefi/UEFI_BSD_P20/uefi_bsd_rel/Signed/x64sas2.efi
>   inflating: /tmp/lsi_uefi/UEFI_BSD_P20/uefi_bsd_rel/Signed/x64sas2.rom
>   inflating: /tmp/lsi_uefi/UEFI_BSD_P20/uefi_bsd_rel/x64sas2.efi
>   inflating: /tmp/lsi_uefi/UEFI_BSD_P20/uefi_bsd_rel/x64sas2.rom
> SAS Address      : 5b8ca3a0ed5ab100
> Using SAS address '5b8ca3a0ed5ab100'
> fatal: destination path 'lsirec' already exists and is not an empty directory.
> make: Entering directory '/home/aki/lsirec'
> make: Nothing to be done for 'all'.
> make: Leaving directory '/home/aki/lsirec'
> 
> 42:00.0 RAID bus controller [0104]: LSI Logic / Symbios Logic MegaRAID SAS 2008 [Falcon] [1000:0073] (rev 03)
> Unbinding and halting device...
> 
> Trying unlock in MPT mode...
> Device in MPT mode
> Device in MPT mode
> Resetting adapter in HCB mode...
> Trying unlock in MPT mode...
> Device in MPT mode
> IOC is RESET
> 
> Backing up SBR...
> 
> Device in MPT mode
> Using I2C address 0x54
> Using EEPROM type 1
> Reading SBR...
> SBR saved to /tmp/5b8ca3a0ed5ab100/5b8ca3a0ed5ab100_backup.sbr
> 
> Extracting SBR config...
> 
> 
> Modifying SBR config...
> 
> 
> Building new SBR...
> 
> 
> Writing modified SBR to device...
> 
> Device in MPT mode
> Using I2C address 0x54
> Using EEPROM type 1
> Writing SBR...
> SBR written from /tmp/5b8ca3a0ed5ab100/5b8ca3a0ed5ab100_modified.sbr
> 
> Writing IT firmware to running image on device...
> 
> Device in MPT mode
> Resetting adapter in HCB mode...
> Trying unlock in MPT mode...
> Device in MPT mode
> IOC is RESET
> Setting up HCB...
> HCDW virtual: 0x7f1b99c00000
> HCDW physical: 0x7ea400000
> Loading firmware...
> Loaded 722708 bytes
> Booting IOC...
> IOC is READY
> IOC Host Boot successful.
> 
> 
> Waiting for IOC to become ready...IOC is READY
> Starting rescan...
> 
> Device in MPT mode
> Removing PCI device...
> Rescanning PCI bus...
> PCI bus rescan complete.
> 
> 
> Waiting for MPT.......... 1.  ioc0              LSI Logic SAS2008 B2      200      14000700     0
> Dumping existing flash...
> 
> 
> LSI Logic MPT Configuration Utility, Version 1.72, Sep 09, 2014
> 
> 1 MPT Port found
> 
>      Port Name         Chip Vendor/Type/Rev    MPT Rev  Firmware Rev  IOC
>  1.  ioc0              LSI Logic SAS2008 B2      200      14000700     0
> 
> Main menu, select an option:  [1-99 or e/p/w or 0 to quit] 46
> 
>  1.  Firmware
>  2.  BIOS/FCode
>  3.  BootLoader
>  4.  Firmware (backup copy)
>  5.  Complete (all sections)
> 
> Select what to upload:  [1-5 or RETURN to quit] 5
> 
> 
> Uploading image...
> 
> Wrote 16777216 bytes to file /tmp/5b8ca3a0ed5ab100/5b8ca3a0ed5ab100_backup.bin
> 
> Main menu, select an option:  [1-99 or e/p/w or 0 to quit] 0
> 
> 
> Waiting for MPT... 1.  ioc0              LSI Logic SAS2008 B2      200      14000700     0
> Erasing flash...
> 
> 
> LSI Logic MPT Configuration Utility, Version 1.72, Sep 09, 2014
> 
> 1 MPT Port found
> 
>      Port Name         Chip Vendor/Type/Rev    MPT Rev  Firmware Rev  IOC
>  1.  ioc0              LSI Logic SAS2008 B2      200      14000700     0
> 
> Main menu, select an option:  [1-99 or e/p/w or 0 to quit] 33
> 
>  1.  NVSRAM
>  2.  SEEPROM
>  3.  FLASH
>  4.  BootLoader
>  5.  Firmware (backup copy)
>  6.  Firmware (current copy)
>  7.  Persistent non-manufacturing config pages
>  8.  Persistent manufacturing config pages
>  9.  Boot services (BIOS/FCode)
> 
> Select what to erase:  [1-9 or RETURN to quit] 3
> 
> Erasing...
> 
>  1.  NVSRAM
>  2.  SEEPROM
>  3.  FLASH
>  4.  BootLoader
>  5.  Firmware (backup copy)
>  6.  Firmware (current copy)
>  7.  Persistent non-manufacturing config pages
>  8.  Persistent manufacturing config pages
>  9.  Boot services (BIOS/FCode)
> 
> Select what to erase:  [1-9 or RETURN to quit] 8
> 
> Erasing...
> 
>  1.  NVSRAM
>  2.  SEEPROM
>  3.  FLASH
>  4.  BootLoader
>  5.  Firmware (backup copy)
>  6.  Firmware (current copy)
>  7.  Persistent non-manufacturing config pages
>  8.  Persistent manufacturing config pages
>  9.  Boot services (BIOS/FCode)
> 
> Select what to erase:  [1-9 or RETURN to quit]
> 
> Main menu, select an option:  [1-99 or e/p/w or 0 to quit] 0
> 
> 
> Waiting for MPT... 1.  ioc0              LSI Logic SAS2008 B2      200      14000700     0
> Flashing IT firmware...
> 
> 
> LSI Logic MPT Configuration Utility, Version 1.72, Sep 09, 2014
> 
> 1 MPT Port found
> 
>      Port Name         Chip Vendor/Type/Rev    MPT Rev  Firmware Rev  IOC
>  1.  ioc0              LSI Logic SAS2008 B2      200      14000700     0
> 
> Main menu, select an option:  [1-99 or e/p/w or 0 to quit] 2
> 
> Firmware image's version is MPTFW-20.00.07.00-IT
>   LSI Logic
>   Not Packaged Yet
>   MPTFW-20.00.07.00-BL
>   LSI Logic
>   Not Packaged Yet
> 
> Do you want to continue?  [Yes or No, default is No] yes
> 
> Downloading image...
> Download succeeded
> 
> Verifying download...
> Verification succeeded
> 
> Main menu, select an option:  [1-99 or e/p/w or 0 to quit] 0
> 
> 
> Waiting for IOC to become ready...IOC is OPERATIONAL
> Resetting device...
> 
> Device in MPT mode
> Kernel driver unbound from device
> Resetting adapter...
> IOC is RESET
> IOC is RESET
> IOC failed to become ready
> Trying unlock in MPT mode...
> Device in MPT mode
> Removing PCI device...
> Rescanning PCI bus...
> PCI bus rescan complete.
> 
> 
> Waiting for MPT.......... 1.  ioc1              LSI Logic SAS2008 B2      200      14000700     0
> Setting WWN/SAS address...
> 
> 
> LSI Logic MPT Configuration Utility, Version 1.72, Sep 09, 2014
> 
> 1 MPT Port found
> 
>      Port Name         Chip Vendor/Type/Rev    MPT Rev  Firmware Rev  IOC
>  1.  ioc1              LSI Logic SAS2008 B2      200      14000700     0
> 
> Main menu, select an option:  [1-99 or e/p/w or 0 to quit] 18
> 
> Current SAS WWID = 0000000000000000
> 
> Enter new WWID:  [16 hex digits or RETURN to quit] 5b8ca3a0ed5ab100
> 
> Main menu, select an option:  [1-99 or e/p/w or 0 to quit] 0
> 
> 
> Waiting for IOC to become ready...IOC is OPERATIONAL
> Resetting device...
> 
> Device in MPT mode
> Kernel driver unbound from device
> Resetting adapter...
> IOC is RESET
> IOC is READY
> Trying unlock in MPT mode...
> Device in MPT mode
> Removing PCI device...
> Rescanning PCI bus...
> PCI bus rescan complete.
> 
> 
> Waiting for MPT.......... 1.  ioc2              LSI Logic SAS2008 B2      200      14000700     0
> Flashing BIOS/UEFI boot ROMs...
> 
> 
> LSI Logic MPT Configuration Utility, Version 1.72, Sep 09, 2014
> 
> 1 MPT Port found
> 
>      Port Name         Chip Vendor/Type/Rev    MPT Rev  Firmware Rev  IOC
>  1.  ioc2              LSI Logic SAS2008 B2      200      14000700     0
> 
> Main menu, select an option:  [1-99 or e/p/w or 0 to quit] 4
> 
> To erase an image:
>   1.  hit RETURN when asked for a image file name
>   2.  answer No if asked to preserve an existing image
> 
> x86 BIOS image's version is MPT2BIOS-7.39.02.00 (2015.08.03)
>   7.39.02.00(2015.08.03)-BIOS txt @(#)LSI Corporation
>   7.39.02.00(2015.08.03)-CU IR exe@(#)LSI Corporation
>   7.39.02.00(2015.08.03)-CU IR txt@(#)LSI Corporation
>   7.39.02.00(2015.08.03)-CU IR opt@(#)LSI Corporation
> 
> No FCode image exists in FLASH, and image won't be downloaded
> 
> EFI BIOS image's version is 7.27.01.01
> 
> Do you want to continue?  [Yes or No, default is No] yes
> 
> Downloading image...
> Download succeeded
> 
> Main menu, select an option:  [1-99 or e/p/w or 0 to quit] 0
> 
> 
> All done. Copy /tmp/5b8ca3a0ed5ab100/ to persistent media and reboot.
> 
> aki@aki-PowerEdge-R720xd:~$
