### ISSUE TITLE
Could not retrieve PCI address from lspci

### ISSUE THREAD

**Issue by BavYeti** [Confusingboat/flash-it#18]
I guess the output format of lspci verbose changed and the script stops with 

> Could not retrieve PCI address from lspci

`man lspci` suggest to use the `-m` flag for machine readable output

**Comment by BavYeti** [comment]
Sorry should have read through all issues #14 mentions this already. Anyway I think my patch is backwards compatible and future proof.

Tested on Ubuntu 20.04

**Comment by Confusingboat** [comment]
I'll be happy to merge in #19 if someone can confirm it also works with 18.04

**Comment by eyeofmaat** [comment]
I need to run this on a R420 soon. I have 2 of them to do.
If you want me to do something specific, let me know.

**Comment by jayeshgarg** [comment]
+1
tested patch with H310 MM on Ubuntu 20.04.1
Few pointers that may help others(specially dummies like me) using this script and patch
1) Run from pen drive or any other drive not connected via RAID controller(H310)
2) Include this patch (https://github.com/Confusingboat/flash-it/pull/19/files)
3) Download the sample CFG file as well and remove ".example" from it
4) May require manual installation of 7z, Git, Libncurses5(all variants), etc

**Comment by Confusingboat** [comment]
Sorry for being so slow with this guys.

@eyeofmaat I just want to make sure the script works without manual steps on both 18.04 and 20.04; perhaps you could test the patch with one R420 each on 18.04 and 20.04? That would be awesome.

@jayeshgarg fyi downloading the sample CFG file shouldn't be necessary (check out the script and you'll see its reference is commented out), I've just left it in the repository as reference. Also, if there are manual package installation steps required with Ubuntu 20.04, let's verify which ones are missing and open another issue with those listed so we can get that piece automated in a manner that's backwards compatible with 18.04.

**Comment by BavYeti** [comment]
@Confusingboat fyi I tested it on a R320 #17 with 20.04 #16 see PR for the Readme

**Comment by eyeofmaat** [comment]
I have a live install of 18.04.5 (LTS i think) on a USB ready to try this, but I dont know github very well. I dont know how to bring in the patch. I can see the 2 lines (147/148) that were changed, so I can manually edit it in VIM unless you can link me some instructions to include it automatically?

**Comment by BavYeti** [comment]
@eyeofmaat you basically clone the patched fork I made. Link is in my PR #19 or you go directly to [https://github.com/BavYeti/flash-it](https://github.com/BavYeti/flash-it)

**Comment by yetkinergun** [comment]
came here to say I also used this branch after running into issues on master - can confirm it worked well on my R720xd with H310MM, using Ubuntu 20 Live.
