### ISSUE TITLE
TESTED: IBM M1015 in Huawei RH2288v2

### ISSUE THREAD

**Issue by Goeny** [Confusingboat/flash-it#20]
We have tested this script with an IBM ServeRAID M1015 card in a Huawei RH2288v2 server.

Ubuntu 18.04 LXDE Live (NetbootXYZ)
Changed the ADAPTER_PATTERN to "M1015"

Works without issues.

**Comment by Confusingboat** [comment]
Awesome! I'll work on getting this added.
