### ISSUE TITLE
Bricked H310 Mini Mono on R720XD

### ISSUE THREAD

**Issue by DPerkunas** [Confusingboat/flash-it#22]
Pretty sure I followed directions, but stuff happened... 
From the very first step of erasing data, it said "erasing failed" and it continued to fail throughout. 

I was booted on Ubuntu LTS usb drive. Ran the scripts,  when I noticed it failed, I did a restore, said successful.

The H310 mini mono was latest dell firmware if it makes a difference.

Bummer.. The error I get at boot says "needs to be reflashed" and "verification failed".

**Comment by tssajo** [comment]
This guy can unbrick it: Art of Server -- Look him up on Youtube.

See:

https://www.youtube.com/watch?v=koyVehVIXA8

https://www.youtube.com/watch?v=NRnsajK99kU

https://www.youtube.com/watch?v=Y1Xi5NZRlXM

**Comment by DPerkunas** [comment]
I was able to fix it after getting the firmware programming device and following his directions. Thanks.
